# -*- restclient -*-
#

# Register a user

POST http://localhost:3001/register
Content-Type: application/json

{
        "username": "user",
        "password": "secret"
}
#


# Login to a user

POST http://localhost:3001/login
Content-Type: application/json

{
        "username": "user",
        "password": "secret"
}
#

# Test JWT authorization, happy path

GET http://localhost:3001/hidden
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NjM2MDQ0MjN9.jUTBHxYTxfO5yF2iip8rBJfY_L8aQBjszW_pPXu5SqQ

# Test JWT authorization, unhappy path

GET http://localhost:3001/hidden
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.cThIIoDvwdueQB468K5xDc5633seEFoqwxjF\ _xSJyQQ

# Test WASM CGI, GET request

GET http://localhost:3001/wasm/hello-cgi.wasm

# Test WASM CGI, GET request with query parameters

GET http://localhost:3001/wasm/hello-cgi.wasm?hello=world

# Test WASM CGI, POST request

POST http://localhost:3001/wasm/hello-cgi.wasm
Content-Type: application/json

{
    "hello": "world"
}

# Test WASM CGI, PUT

PUT http://localhost:3001/wasm/hello-cgi.wasm
Content-Type: application/json

{
    "hello": "world"
}


# Test WASM CGI, POST request, namespaced

POST http://localhost:3001/wasm/samsai/hello-cgi.wasm
Content-Type: application/json

{
    "hello": "world"
}


# Test WASM CGI, POST request, namespaced, token protected

POST http://localhost:3001/wasm/samsai/add-json.wasm
Content-Type: application/json
Authorization: Bearer 74873142-4fdd-47db-b6f4-e6016b0558d8

{
    "numbers": [1, 1]
}

# Test WASM CGI, POST request, namespaced, token protected, incorrect token

POST http://localhost:3001/wasm/samsai/add-json.wasm
Content-Type: application/json
Authorization: Bearer Wrong

{
    "numbers": [1, 1]
}